import apiRouter from './api.routes';
import dataRouter from './data.routes';
import rohligPlRouter from './rohligpl.routes';
import docsRouter from './docs.routes';
import ftpRouter from './ftp.routes';
import transpackRouter from './transpack.routes';
export const api = apiRouter;
export const data = dataRouter;
export const docs = docsRouter;
export const ftp = ftpRouter;
export const rohligPl = rohligPlRouter;
export const transpack = transpackRouter;